name: run-repo
run-name: "run `sundrylint` for ${{github.event.inputs.repo_url}}"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "the repo to run linter"
        default: "https://github.com/alingse/sundrylint"
        required: true

permissions:
  issues: write

jobs:
  go-linter-runner-for-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run go-linter-runner use direct job config
        uses: alingse/go-linter-runner@main
        with:
          action: run
          go_version: "1.24.0"
          install_command: go build -o /usr/local/bin/sundrylint cmd/sundrylint/main.go
          linter_command: sundrylint
          includes: "[\"call regexp.MustCompile with constant should be moved out of func\"]"
          excludes: "[]"
          issue_id: 7
          repo_url: ${{ inputs.repo_url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
